import axios from "axios";
import Head from "next/head";
import HomeHeader from "../components/HomeHeader";
import HomeLatestPosts from "../components/HomeLatestPosts";

export default function Home({ posts }) {
  console.log("posts", posts);
  return (
    <>
      <Head>
        <title>Devistry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeader />
      <HomeLatestPosts posts={posts} />
    </>
  );
}

// getStaticProps can be use just in the page folder
export async function getStaticProps() {
  const { data } = await axios.get("http://localhost:1337/api/posts");
  return {
    props: {
      posts: data.data,
    },
  };
}
